all:
  children:
    cml_routers:
      hosts:
        CSR1:
          ansible_host: 192.168.1.6
          ansible_user: cisco
          ansible_password: cisco
          ansible_connection: network_cli
          ansible_network_os: ios     

        CSR2:
          ansible_host: 10.0.12.2
          ansible_user: cisco
          ansible_password: cisco
          ansible_connection: network_cli
          ansible_network_os: ios  