---

- name: Backup Cisco IOS Configurations
  hosts: cml_routers
  gather_facts: no
  connection: network_cli


  tasks:
    - name: Backup running-config t0 local folder
      ios_config:
        backup: yes
        backup_options: 
          filename: "{{ inventory_hostname }}-backup.cfg"
          dir_path: "./backups/" 